openapi: 3.0.0
info:
  title: Chart Tax REST API
  version: 1.0.0
  description: The documentation for Chart Tax API.
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /authorize:
    post:
      summary: Authorize OAuth2
      responses:
        '200':
          description: Successful operation
  /auth/token:
    post:
      summary: Get OAuth2 token
      responses:
        '200':
          description: Successful operation
  /records:
    get:
      summary: Get tax records
      responses:
        '200':
          description: Successful operation
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth2/authorize
          tokenUrl: https://example.com/oauth2/token
          scopes: {}
security:
  - OAuth2: []